import type { TimelineStep, FounderStage, MirrorMessage } from "./types";

export const customer = {
  name: "Mei Tan",
  age: 32,
  role: "Senior Product Designer (Stripe) + founder of Kopi Studio (sole-prop, ACRA registered 2025-09-14)",
  salaryMonthly: 11800,
  sideMonthly: 3200,
  baseCurrency: "SGD",
  city: "Singapore",
  segmentNote: "Treasures pipeline, eligible in approx. 18 months at current trajectory",
};

export const mirrorMessages: Record<string, MirrorMessage> = {
  base: {
    language: "Singlish",
    text:
      "Eh future-me here. At this rate I retire okay lah, but Kopi Studio still small. Push more into it now, your 65-year-old self got more story to tell.",
    mood: "worried",
    gapClosedPct: 38,
  },
  improved: {
    language: "Singlish",
    text:
      "Future-me reporting. Last 12 months you ran the plan, you topped up SRS, you funded Kopi Studio. I retire comfortable and Kopi Studio is a real thing. Solid lah.",
    mood: "proud",
    gapClosedPct: 86,
  },
};

export const timeline: TimelineStep[] = [
  {
    id: "t1",
    day: 2,
    title: "FX sweep SGD to GBP",
    amount: "SGD 1,200 to GBP 695",
    destination: "GBP holding account",
    reversibility: "auto",
    triggerRule: "Keep GBP balance above 800. Sweep when rate beats 0.578.",
    whyContributions: [
      { label: "live rate 0.579", weight: 88 },
      { label: "GBP balance 612", weight: 71 },
      { label: "salary FX cost this month", weight: 44 },
    ],
    confidence: 91,
    counterfactual: "If rate dropped to 0.560 the sweep would pause and you would be notified.",
    status: "scheduled",
    petals: ["Information", "Order-taking", "Payment", "Billing"],
    aisaqual: ["Reliability", "Personalisation", "Transparency"],
  },
  {
    id: "t2",
    day: 9,
    title: "Pay DBS Altitude card in full",
    amount: "SGD 2,418",
    destination: "Altitude card 4621",
    reversibility: "oneTap",
    triggerRule: "Pay the card in full from main account two days before due.",
    whyContributions: [
      { label: "statement closed", weight: 92 },
      { label: "main account buffer", weight: 70 },
      { label: "interest avoided 26 percent APR", weight: 65 },
    ],
    confidence: 96,
    counterfactual: "If main account would dip below SGD 8,000 buffer, only minimum due would be auto-paid.",
    status: "scheduled",
    petals: ["Order-taking", "Payment", "Billing"],
    aisaqual: ["Reliability", "Transparency"],
  },
  {
    id: "t3",
    day: 14,
    title: "Kopi Studio inventory advance",
    amount: "SGD 4,500",
    destination: "Kopi Studio business current",
    reversibility: "oneTap",
    triggerRule: "When Founder pipeline approves a tranche, release working capital to business account.",
    whyContributions: [
      { label: "approved tranche from Founder", weight: 95 },
      { label: "Shopify receivables next 14d", weight: 78 },
      { label: "no chargebacks last 90d", weight: 62 },
    ],
    confidence: 89,
    counterfactual: "If Shopify receivables drop below SGD 3,000 the release pauses and asks for review.",
    status: "scheduled",
    petals: ["Order-taking", "Payment", "Consultation"],
    aisaqual: ["Reliability", "Personalisation", "Transparency"],
  },
  {
    id: "t4",
    day: 18,
    title: "SRS top-up by 31 Dec",
    amount: "SGD 15,300",
    destination: "DBS SRS account",
    reversibility: "biometric",
    triggerRule: "Top up SRS to the annual cap before 31 December if taxable income is above 80k and cash buffer holds.",
    whyContributions: [
      { label: "taxable income SGD 142k", weight: 86 },
      { label: "SRS balance SGD 0 ytd", weight: 81 },
      { label: "tax saving estimate SGD 2,295", weight: 73 },
    ],
    confidence: 88,
    counterfactual: "If buffer drops below SGD 6,000 the top-up halves and you are alerted.",
    status: "scheduled",
    petals: ["Information", "Consultation", "Order-taking", "Payment", "Safekeeping"],
    aisaqual: ["Reliability", "Personalisation", "Transparency", "Security"],
  },
  {
    id: "t5",
    day: 24,
    title: "Sweep above emergency floor to digiPortfolio",
    amount: "SGD 3,100",
    destination: "digiPortfolio Growth Plus",
    reversibility: "auto",
    triggerRule: "Anything above SGD 12,000 emergency floor moves into digiPortfolio Growth Plus weekly.",
    whyContributions: [
      { label: "buffer above floor", weight: 84 },
      { label: "digiPortfolio drift below band", weight: 52 },
      { label: "salary credited 25 Dec", weight: 49 },
    ],
    confidence: 93,
    counterfactual: "If buffer drops below floor, sweep pauses and you keep your safety cushion.",
    status: "scheduled",
    petals: ["Information", "Order-taking", "Payment", "Safekeeping"],
    aisaqual: ["Reliability", "Personalisation", "Security"],
  },
  {
    id: "t6",
    day: 28,
    title: "Parents allowance to mum",
    amount: "SGD 800",
    destination: "Tan Lai Heng (POSB savings)",
    reversibility: "oneTap",
    triggerRule: "Monthly allowance transfer to mum, day 28.",
    whyContributions: [
      { label: "recurring rule, 14 months consistent", weight: 99 },
      { label: "buffer healthy", weight: 64 },
    ],
    confidence: 99,
    counterfactual: "If main account dips below floor the transfer is delayed by 48 hours and you are asked to confirm.",
    status: "scheduled",
    petals: ["Order-taking", "Payment", "Hospitality"],
    aisaqual: ["Reliability", "Personalisation"],
  },
];

export const founderStages: FounderStage[] = [
  {
    id: "f1",
    index: 1,
    title: "Connect Xero and Shopify",
    status: "approved",
    artifact: "Imported 18 months of Kopi Studio books and 312 Shopify orders. Average monthly revenue SGD 4,600 trending up 18 percent QoQ.",
    reasoning: "Read-only OAuth. Used to ground every later step in real numbers, not estimates.",
    petals: ["Information", "Safekeeping"],
    aisaqual: ["Reliability", "Security"],
  },
  {
    id: "f2",
    index: 2,
    title: "Draft 12-month cashflow forecast",
    status: "review",
    artifact:
      "Forecast: revenue SGD 73k, COGS SGD 31k, opex SGD 18k, net SGD 24k. Sensitivity tested on minus 30 percent revenue still keeps positive operating cash.",
    reasoning: "Forecast uses your real seasonality. Hari Raya, NDP, and Christmas peaks weighted on three years of Shopify history.",
    petals: ["Information", "Consultation"],
    aisaqual: ["Personalisation", "Transparency"],
  },
  {
    id: "f3",
    index: 3,
    title: "Write the credit narrative",
    status: "drafting",
    artifact:
      "Kopi Studio is a Singapore-based small-batch ceramics brand. Inventory financing of SGD 35k is requested to fund a six-month build for the Q3 Tokyo pop-up. Repayment is keyed to Shopify daily settlement at three percent of gross sales.",
    reasoning: "Plain English, founder voice, written from your books. You edit any sentence before it is sent.",
    petals: ["Order-taking", "Consultation", "Hospitality"],
    aisaqual: ["Personalisation", "Anthropomorphism", "Transparency"],
  },
  {
    id: "f4",
    index: 4,
    title: "Propose covenants and pricing",
    status: "pending",
    artifact:
      "Suggested: revenue-share repayment 3 percent of Shopify gross, cap SGD 41k, no personal guarantee, 12-month term.",
    reasoning: "Comparable to Shopify Capital and SME loans on IDEAL; benchmark spread cited.",
    petals: ["Billing", "Consultation"],
    aisaqual: ["Reliability", "Transparency"],
  },
  {
    id: "f5",
    index: 5,
    title: "Run the FEAT and AI Verify check",
    status: "pending",
    artifact:
      "Pre-decision bias check: no prohibited variables used (gender, race, religion, marital status). FEAT memo auto-generated. AI Verify test report attached.",
    reasoning: "MAS FEAT requirement. Visible to you before you submit.",
    petals: ["Information", "Safekeeping"],
    aisaqual: ["Transparency", "Security", "Reliability"],
  },
  {
    id: "f6",
    index: 6,
    title: "You review and approve the application",
    status: "pending",
    artifact: "Single signed PDF assembled from approved sections. Edits tracked.",
    reasoning: "You own every page. Biometric signature with 10-second cool-off, like Plan irreversibles.",
    petals: ["Order-taking", "Safekeeping", "Exceptions"],
    aisaqual: ["Security", "Reliability"],
  },
  {
    id: "f7",
    index: 7,
    title: "DBS underwriting decision",
    status: "pending",
    artifact: "Indicative decision in 4 working hours, final in 48 hours. Decision feeds into Plan as approved tranche.",
    reasoning: "Hand-off to DBS CreditAI plus a human credit officer. Decision explanation returned.",
    petals: ["Information", "Consultation"],
    aisaqual: ["Reliability", "Transparency"],
  },
  {
    id: "f8",
    index: 8,
    title: "Disbursement linked to Plan",
    status: "pending",
    artifact: "If approved, funds release card t3 in Plan turns active. You see the link both ways.",
    reasoning: "Closes the loop from Founder back to Plan. One product, one customer.",
    petals: ["Payment", "Order-taking", "Exceptions"],
    aisaqual: ["Reliability", "Transparency"],
  },
];

export const aisaqualGlossary: Record<string, string> = {
  Reliability: "The agent does what it said it would do, on the trigger conditions you set.",
  Personalisation: "Decisions are grounded in your real cashflow, rules, and goals.",
  Anthropomorphism: "The Mirror has a face, a voice, and speaks in your parlance.",
  Tangibility: "Visual, scannable, no hidden state. You can point at every choice.",
  Transparency: "Every card opens to show data, weights, confidence, and counterfactual.",
  Security: "Biometric on irreversible actions, 10-second cool-off, freeze switch, audit log.",
};

export const petalGlossary: Record<string, string> = {
  Information: "Curated, contextual data shown before a decision.",
  "Order-taking": "Customer states intent; system confirms and queues.",
  Billing: "Statements, receipts, fee schedules shown clearly.",
  Payment: "Money moves on the stated rule.",
  Consultation: "Advice grounded in customer-specific evidence.",
  Hospitality: "Tone, parlance, warmth, branch hand-off.",
  Safekeeping: "Custody of funds, identity, and data.",
  Exceptions: "Overrides, freezes, complaints, human escalation.",
};
